language: node_js
node_js: stable
sudo: required
cache:
  directories:
  - node_modules
branches:
  only:
  - master
before_install:
- git clone https://${ACCESS_TOKEN}@github.com/0x4f5da2/Blog-Hexo.git
- mkdir Blog-Hexo/source
- cp -r _posts Blog-Hexo/source
- npm install -g hexo-cli
install:
- cd Blog-Hexo
- npm install
- npm install hexo-deployer-git --save
- sed -i "s/valine_appid/${VALINE_APPID}/g" ./themes/next/_config.yml
- sed -i "s/valine_appkey/${VALINE_APPKEY}/g" ./themes/next/_config.yml
- sed -i "s/tencent_analytics_id/${ANALYTICS_ID}/g" ./themes/next/_config.yml
- sed -i "s/tencent_mta_id/${MTA_ID}/g" ./themes/next/_config.yml
script:
- hexo clean
- hexo generate
after_script:
- git config --global user.name "${GIT_NAME}"
- git config --global user.email "${GIT_EMAIL}"
- sed -i "s/access_token/${ACCESS_TOKEN}/g" ./_config.yml
- echo "blog.4f5da2.com" > ./public/CNAME
- hexo deploy