language: node_js
sudo: required
cache:
  directories:
  - node_modules
branches:
  only:
  - master
before_install:
- npm install -g hexo-cli
install:
- git clone https://${ACCESS_TOKEN}@github.com/0x4f5da2/Blog-Hexo.git
- mkdir Blog-Hexo/source
- ls
- cp -r _post Blog-Hexo/source
- cd Blog-Hexo
- npm install
- npm install hexo-deployer-git --save
script:
- hexo clean
- hexo generate
after_script:
- git config user.name "${GIT_NAME}"
- git config user.email "${GIT_EMAIL}"
- sed -i "s/access_token/${ACCESS_TOKEN}/g" ./_config.yml
- hexo deploy
